#
# k8s-cms
# Kubernetes Intergration
# Service Account
# 

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.security.serviceAccount.name }}
  labels:
    app: k8s-cms 
automountServiceAccountToken: false
