#
# k8s-cms
# Kubernetes Intergration
# ConfigMap with configuration files
# 

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-cms.fullname" . }}-config-file
  labels:
{{ include "k8s-cms.labels" . | indent 4 }}
data:
  "cms.conf": |-
{{ .Files.Get "config/cms.conf" | indent 4 }}
  "cms.ranking.conf": |-
{{ .Files.Get "config/cms.ranking.conf" | indent 4 }}
