#
# k8s-cms
# Kubernetes Intergration
# CMS Web Ranking Interface
#

apiVersion:  apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-cms.fullname" . }}-web-ranking
  labels:
{{ include "k8s-cms.labels" . | indent 4 }}
    component: ranking
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "k8s-cms.selectors" . | indent 6 }}
      component: ranking
  template:
    metadata:
      labels:
{{ include "k8s-cms.labels" . | indent 8 }}
        component: ranking
      annotations:
{{ include "k8s-cms.annotations" . | indent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      serviceAccountName: {{ .Values.security.serviceAccount.name }}
      containers:
        {{- with .Values.images.ranking }}
        - name: {{ .name }}
          image: {{ .repository }}:{{ .tag }}
        {{- end }}
          ports:
            - name: cmsrank
              containerPort: 8890
          envFrom:
            - configMapRef:
                name: {{ include "k8s-cms.fullname" . }}-config-env
          env:
            # inject ranking credentials
            - name: CMS_RANKING_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8s-cms.fullname" . }}-secrets
                  key: CMS_RANKING_USER
            - name: CMS_RANKING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8s-cms.fullname" . }}-secrets
                  key: CMS_RANKING_PASSWORD
          livenessProbe:
            httpGet:
              port: cmsrank
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: cmsrank
            periodSeconds: 3

          resources:
{{ toYaml .Values.resources.ranking | indent 12 }}

          volumeMounts:
            - name: config-file
              mountPath: "/cms/config"
      volumes:
        - name: config-file
          configMap:
            name: {{ include "k8s-cms.fullname" . }}-config-file
