#
# k8s-cms
# Kubernetes Intergration
# CMS Printing Deployment 
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-cms.fullname" . }}-printing
  labels:
{{ include "k8s-cms.labels" . | indent 4 }}
    component: printing
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "k8s-cms.selectors" . | indent 6 }}
      component: printing
  template:
    metadata:
      labels:
{{ include "k8s-cms.labels" . | indent 8 }}
        component: printing
      annotations:
{{ include "k8s-cms.annotations" . | indent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      serviceAccountName: {{ .Values.security.serviceAccount.name }}
      containers:
        {{- with .Values.images.printing }}
        - name: {{ .name }}
          image: {{ .repository }}:{{ .tag }}
        {{- end }}
          ports:
            - name: cmsprint
              containerPort: 25123
          envFrom:
            - configMapRef:
                name: {{ include "k8s-cms.fullname" . }}-config-env
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8s-cms.fullname" . }}-secrets
                  key: POSTGRES_PASSWORD
            # required for container to listen
            - name: CMS_PRINTING
              value: "0.0.0.0"
          livenessProbe:
            tcpSocket:
              port: cmsprint
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: cmsprint
            periodSeconds: 3

          resources:
{{ toYaml .Values.resources.printing | indent 12 }}

          volumeMounts:
            - name: config-file
              mountPath: "/cms/config"
      volumes:
        - name: config-file
          configMap:
            name: {{ include "k8s-cms.fullname" . }}-config-file
