#
# k8s-cms
# Kubernetes Intergration
# CMS Checker Service
#

apiVersion:  apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-cms.fullname" . }}-checker
  labels:
{{ include "k8s-cms.labels" . | indent 4 }}
    component: checker
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "k8s-cms.selectors" . | indent 6 }}
      component: checker
  template:
    metadata:
      labels:
{{ include "k8s-cms.labels" . | indent 8 }}
        component: checker
      annotations:
{{ include "k8s-cms.annotations" . | indent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      serviceAccountName: {{ .Values.security.serviceAccount.name }}
      containers:
        {{- with .Values.images.checker }}
        - name: {{ .name }}
          image: {{ .repository }}:{{ .tag }}
        {{- end }}
          ports:
            # port used by checker
            - name: cmscheck
              containerPort: 22000
          envFrom:
            - configMapRef:
                name: {{ include "k8s-cms.fullname" . }}-config-env
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8s-cms.fullname" . }}-secrets
                  key: POSTGRES_PASSWORD
            # required for container to listen
            - name: CMS_CHECKER
              value: "0.0.0.0"
          
          livenessProbe:
            tcpSocket:
              port: cmscheck
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: cmscheck
            periodSeconds: 3

          resources:
{{ toYaml .Values.resources.checker | indent 12 }}

          volumeMounts:
            - name: config-file
              mountPath: "/cms/config"
      volumes:
        - name: config-file
          configMap:
            name: {{ include "k8s-cms.fullname" . }}-config-file
