#
# k8s-cms
# Kubernetes Intergration
# CMS Contest Web Interface Deployment
#

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "k8s-cms.fullname" . }}-web-contest-autoscaler
  labels:
{{ include "k8s-cms.labels" . | indent 4 }}
    component: contest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "k8s-cms.fullname" . }}-web-contest
  minReplicas: {{ .Values.replicas.contest.minCount }}
  maxReplicas: {{ .Values.replicas.contest.maxCount }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 80
