#
# k8s-cms
# Kubernetes Intergration
# CMS Contest Web Interface Deployment
#

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "k8s-cms.fullname" . }}-worker-autoscaler
  labels:
{{ include "k8s-cms.labels" . | indent 4 }}
    component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "k8s-cms.fullname" . }}-worker
  minReplicas: {{ .Values.replicas.worker.minCount }}
  maxReplicas: {{ .Values.replicas.worker.maxCount }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 95
