#
# k8s-cms
# Kubernetes Intergration
# CMS Scoring Service
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.scoring.name }}
  labels:
{{ include "k8s-cms.labels" . | indent 4 }}
    component: scoring
spec:
  type: {{ .Values.services.scoring.type }}
  selector:
{{ include "k8s-cms.selectors" . | indent 4 }}
    component: scoring
  ports:
    - name: cmsscore
      port: 28500
      targetPort: 28500
