#
# k8s-cms
# Kubernetes Intergration
# CMS Ranking Service
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.ranking.name }}
  labels:
{{ include "k8s-cms.labels" . | indent 4 }}
    component: ranking
spec:
  type: {{ .Values.services.ranking.type }}
  selector:
{{ include "k8s-cms.selectors" . | indent 4 }}
    component: ranking
  ports:
    - name: cmsrank
      port: 8890
      targetPort: 8890
