#
# k8s-cms
# Kubernetes Intergration
# CMS Evaluation Service
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.evaluation.name }}
  labels:
{{ include "k8s-cms.labels" . | indent 4 }}
    component: evaluation
spec:
  type: {{ .Values.services.evaluation.type }}
  selector:
{{ include "k8s-cms.selectors" . | indent 4 }}
    component: evaluation
  ports:
    - name: cmseval
      port: 25000
      targetPort: 25000
