#
# k8s-cms
# Kubernetes Intergration
# CMS Proxy Service
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.proxy.name }}
  labels:
{{ include "k8s-cms.labels" . | indent 4 }}
    component: proxy
spec:
  type: {{ .Values.services.proxy.type }}
  selector:
{{ include "k8s-cms.selectors" . | indent 4 }}
    component: proxy
  ports:
    - name: cmsproxy
      port: 28600
      targetPort: 28600
