#
# k8s-cms
# Kubernetes Intergration
# CMS Contest Service
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.contest.name }}
  labels:
{{ include "k8s-cms.labels" . | indent 4 }}
    component: contest
spec:
  type: {{ .Values.services.contest.type }}
  selector:
{{ include "k8s-cms.selectors" . | indent 4 }}
    component: contest
  ports:
    - name: cmscontest
      port: 21000
      targetPort: 21000
