#
# k8s-cms
# Kubernetes Intergration
# Secrets
#

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-cms.fullname" . }}-secrets
  labels:
{{ include "k8s-cms.labels" . | indent 4 }}
stringData:
  {{- .Files.Get ".env" | replace "=" ": " | nindent 2 -}}
